//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AracWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Arac", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Arac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        private int EhliyetYasiField;
        
        private int MinYasSiniriField;
        
        private int GunlukSinirKMField;
        
        private int KendiAnlikKMField;
        
        private bool AirbagField;
        
        private int BagajHacmiField;
        
        private int KoltukSayisiField;
        
        private int GunlukKiralikFiyatField;
        
        private int SirketIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int EhliyetYasi {
            get {
                return this.EhliyetYasiField;
            }
            set {
                if ((this.EhliyetYasiField.Equals(value) != true)) {
                    this.EhliyetYasiField = value;
                    this.RaisePropertyChanged("EhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MinYasSiniri {
            get {
                return this.MinYasSiniriField;
            }
            set {
                if ((this.MinYasSiniriField.Equals(value) != true)) {
                    this.MinYasSiniriField = value;
                    this.RaisePropertyChanged("MinYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GunlukSinirKM {
            get {
                return this.GunlukSinirKMField;
            }
            set {
                if ((this.GunlukSinirKMField.Equals(value) != true)) {
                    this.GunlukSinirKMField = value;
                    this.RaisePropertyChanged("GunlukSinirKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int KendiAnlikKM {
            get {
                return this.KendiAnlikKMField;
            }
            set {
                if ((this.KendiAnlikKMField.Equals(value) != true)) {
                    this.KendiAnlikKMField = value;
                    this.RaisePropertyChanged("KendiAnlikKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Airbag {
            get {
                return this.AirbagField;
            }
            set {
                if ((this.AirbagField.Equals(value) != true)) {
                    this.AirbagField = value;
                    this.RaisePropertyChanged("Airbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int GunlukKiralikFiyat {
            get {
                return this.GunlukKiralikFiyatField;
            }
            set {
                if ((this.GunlukKiralikFiyatField.Equals(value) != true)) {
                    this.GunlukKiralikFiyatField = value;
                    this.RaisePropertyChanged("GunlukKiralikFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracWebService.AracWebServiceSoap")]
    public interface AracWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        WindowsFormsApp1.AracWebService.InsertCustomerResponse InsertCustomer(WindowsFormsApp1.AracWebService.InsertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.InsertCustomerResponse> InsertCustomerAsync(WindowsFormsApp1.AracWebService.InsertCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        WindowsFormsApp1.AracWebService.UpdateCustomerResponse UpdateCustomer(WindowsFormsApp1.AracWebService.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.UpdateCustomerResponse> UpdateCustomerAsync(WindowsFormsApp1.AracWebService.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        bool DeleteCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int id);
        
        // CODEGEN: Generating message contract since element name SelectAllCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCustomers", ReplyAction="*")]
        WindowsFormsApp1.AracWebService.SelectAllCustomersResponse SelectAllCustomers(WindowsFormsApp1.AracWebService.SelectAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.SelectAllCustomersResponse> SelectAllCustomersAsync(WindowsFormsApp1.AracWebService.SelectAllCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name SelectCustomerByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCustomerById", ReplyAction="*")]
        WindowsFormsApp1.AracWebService.SelectCustomerByIdResponse SelectCustomerById(WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCustomerById", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.SelectCustomerByIdResponse> SelectCustomerByIdAsync(WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomer", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.InsertCustomerRequestBody Body;
        
        public InsertCustomerRequest() {
        }
        
        public InsertCustomerRequest(WindowsFormsApp1.AracWebService.InsertCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.AracWebService.Arac entity;
        
        public InsertCustomerRequestBody() {
        }
        
        public InsertCustomerRequestBody(WindowsFormsApp1.AracWebService.Arac entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.InsertCustomerResponseBody Body;
        
        public InsertCustomerResponse() {
        }
        
        public InsertCustomerResponse(WindowsFormsApp1.AracWebService.InsertCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertCustomerResult;
        
        public InsertCustomerResponseBody() {
        }
        
        public InsertCustomerResponseBody(bool InsertCustomerResult) {
            this.InsertCustomerResult = InsertCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.UpdateCustomerRequestBody Body;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(WindowsFormsApp1.AracWebService.UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.AracWebService.Arac entity;
        
        public UpdateCustomerRequestBody() {
        }
        
        public UpdateCustomerRequestBody(WindowsFormsApp1.AracWebService.Arac entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.UpdateCustomerResponseBody Body;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(WindowsFormsApp1.AracWebService.UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCustomerResult;
        
        public UpdateCustomerResponseBody() {
        }
        
        public UpdateCustomerResponseBody(bool UpdateCustomerResult) {
            this.UpdateCustomerResult = UpdateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCustomers", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.SelectAllCustomersRequestBody Body;
        
        public SelectAllCustomersRequest() {
        }
        
        public SelectAllCustomersRequest(WindowsFormsApp1.AracWebService.SelectAllCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllCustomersRequestBody {
        
        public SelectAllCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.SelectAllCustomersResponseBody Body;
        
        public SelectAllCustomersResponse() {
        }
        
        public SelectAllCustomersResponse(WindowsFormsApp1.AracWebService.SelectAllCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.AracWebService.Arac[] SelectAllCustomersResult;
        
        public SelectAllCustomersResponseBody() {
        }
        
        public SelectAllCustomersResponseBody(WindowsFormsApp1.AracWebService.Arac[] SelectAllCustomersResult) {
            this.SelectAllCustomersResult = SelectAllCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCustomerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCustomerById", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.SelectCustomerByIdRequestBody Body;
        
        public SelectCustomerByIdRequest() {
        }
        
        public SelectCustomerByIdRequest(WindowsFormsApp1.AracWebService.SelectCustomerByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCustomerByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SelectCustomerByIdRequestBody() {
        }
        
        public SelectCustomerByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCustomerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCustomerByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.AracWebService.SelectCustomerByIdResponseBody Body;
        
        public SelectCustomerByIdResponse() {
        }
        
        public SelectCustomerByIdResponse(WindowsFormsApp1.AracWebService.SelectCustomerByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCustomerByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.AracWebService.Arac SelectCustomerByIdResult;
        
        public SelectCustomerByIdResponseBody() {
        }
        
        public SelectCustomerByIdResponseBody(WindowsFormsApp1.AracWebService.Arac SelectCustomerByIdResult) {
            this.SelectCustomerByIdResult = SelectCustomerByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracWebServiceSoapChannel : WindowsFormsApp1.AracWebService.AracWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracWebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.AracWebService.AracWebServiceSoap>, WindowsFormsApp1.AracWebService.AracWebServiceSoap {
        
        public AracWebServiceSoapClient() {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.AracWebService.InsertCustomerResponse WindowsFormsApp1.AracWebService.AracWebServiceSoap.InsertCustomer(WindowsFormsApp1.AracWebService.InsertCustomerRequest request) {
            return base.Channel.InsertCustomer(request);
        }
        
        public bool InsertCustomer(WindowsFormsApp1.AracWebService.Arac entity) {
            WindowsFormsApp1.AracWebService.InsertCustomerRequest inValue = new WindowsFormsApp1.AracWebService.InsertCustomerRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.InsertCustomerRequestBody();
            inValue.Body.entity = entity;
            WindowsFormsApp1.AracWebService.InsertCustomerResponse retVal = ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).InsertCustomer(inValue);
            return retVal.Body.InsertCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.InsertCustomerResponse> WindowsFormsApp1.AracWebService.AracWebServiceSoap.InsertCustomerAsync(WindowsFormsApp1.AracWebService.InsertCustomerRequest request) {
            return base.Channel.InsertCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.InsertCustomerResponse> InsertCustomerAsync(WindowsFormsApp1.AracWebService.Arac entity) {
            WindowsFormsApp1.AracWebService.InsertCustomerRequest inValue = new WindowsFormsApp1.AracWebService.InsertCustomerRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.InsertCustomerRequestBody();
            inValue.Body.entity = entity;
            return ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).InsertCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.AracWebService.UpdateCustomerResponse WindowsFormsApp1.AracWebService.AracWebServiceSoap.UpdateCustomer(WindowsFormsApp1.AracWebService.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public bool UpdateCustomer(WindowsFormsApp1.AracWebService.Arac entity) {
            WindowsFormsApp1.AracWebService.UpdateCustomerRequest inValue = new WindowsFormsApp1.AracWebService.UpdateCustomerRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.UpdateCustomerRequestBody();
            inValue.Body.entity = entity;
            WindowsFormsApp1.AracWebService.UpdateCustomerResponse retVal = ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).UpdateCustomer(inValue);
            return retVal.Body.UpdateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.UpdateCustomerResponse> WindowsFormsApp1.AracWebService.AracWebServiceSoap.UpdateCustomerAsync(WindowsFormsApp1.AracWebService.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.UpdateCustomerResponse> UpdateCustomerAsync(WindowsFormsApp1.AracWebService.Arac entity) {
            WindowsFormsApp1.AracWebService.UpdateCustomerRequest inValue = new WindowsFormsApp1.AracWebService.UpdateCustomerRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.UpdateCustomerRequestBody();
            inValue.Body.entity = entity;
            return ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).UpdateCustomerAsync(inValue);
        }
        
        public bool DeleteCustomer(int id) {
            return base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.AracWebService.SelectAllCustomersResponse WindowsFormsApp1.AracWebService.AracWebServiceSoap.SelectAllCustomers(WindowsFormsApp1.AracWebService.SelectAllCustomersRequest request) {
            return base.Channel.SelectAllCustomers(request);
        }
        
        public WindowsFormsApp1.AracWebService.Arac[] SelectAllCustomers() {
            WindowsFormsApp1.AracWebService.SelectAllCustomersRequest inValue = new WindowsFormsApp1.AracWebService.SelectAllCustomersRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.SelectAllCustomersRequestBody();
            WindowsFormsApp1.AracWebService.SelectAllCustomersResponse retVal = ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).SelectAllCustomers(inValue);
            return retVal.Body.SelectAllCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.SelectAllCustomersResponse> WindowsFormsApp1.AracWebService.AracWebServiceSoap.SelectAllCustomersAsync(WindowsFormsApp1.AracWebService.SelectAllCustomersRequest request) {
            return base.Channel.SelectAllCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.SelectAllCustomersResponse> SelectAllCustomersAsync() {
            WindowsFormsApp1.AracWebService.SelectAllCustomersRequest inValue = new WindowsFormsApp1.AracWebService.SelectAllCustomersRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.SelectAllCustomersRequestBody();
            return ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).SelectAllCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.AracWebService.SelectCustomerByIdResponse WindowsFormsApp1.AracWebService.AracWebServiceSoap.SelectCustomerById(WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest request) {
            return base.Channel.SelectCustomerById(request);
        }
        
        public WindowsFormsApp1.AracWebService.Arac SelectCustomerById(int id) {
            WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest inValue = new WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.SelectCustomerByIdRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.AracWebService.SelectCustomerByIdResponse retVal = ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).SelectCustomerById(inValue);
            return retVal.Body.SelectCustomerByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.SelectCustomerByIdResponse> WindowsFormsApp1.AracWebService.AracWebServiceSoap.SelectCustomerByIdAsync(WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest request) {
            return base.Channel.SelectCustomerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.AracWebService.SelectCustomerByIdResponse> SelectCustomerByIdAsync(int id) {
            WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest inValue = new WindowsFormsApp1.AracWebService.SelectCustomerByIdRequest();
            inValue.Body = new WindowsFormsApp1.AracWebService.SelectCustomerByIdRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.AracWebService.AracWebServiceSoap)(this)).SelectCustomerByIdAsync(inValue);
        }
    }
}
