//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaSOAP.RezervWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Arac", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Arac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        private int EhliyetYasiField;
        
        private int MinYasSiniriField;
        
        private int GunlukSinirKMField;
        
        private int KendiAnlikKMField;
        
        private bool AirbagField;
        
        private int BagajHacmiField;
        
        private int KoltukSayisiField;
        
        private decimal GunlukKiralikFiyatField;
        
        private int SirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdiField;
        
        private bool RezerveDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracId {
            get {
                return this.AracIdField;
            }
            set {
                if ((this.AracIdField.Equals(value) != true)) {
                    this.AracIdField = value;
                    this.RaisePropertyChanged("AracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EhliyetYasi {
            get {
                return this.EhliyetYasiField;
            }
            set {
                if ((this.EhliyetYasiField.Equals(value) != true)) {
                    this.EhliyetYasiField = value;
                    this.RaisePropertyChanged("EhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int MinYasSiniri {
            get {
                return this.MinYasSiniriField;
            }
            set {
                if ((this.MinYasSiniriField.Equals(value) != true)) {
                    this.MinYasSiniriField = value;
                    this.RaisePropertyChanged("MinYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int GunlukSinirKM {
            get {
                return this.GunlukSinirKMField;
            }
            set {
                if ((this.GunlukSinirKMField.Equals(value) != true)) {
                    this.GunlukSinirKMField = value;
                    this.RaisePropertyChanged("GunlukSinirKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int KendiAnlikKM {
            get {
                return this.KendiAnlikKMField;
            }
            set {
                if ((this.KendiAnlikKMField.Equals(value) != true)) {
                    this.KendiAnlikKMField = value;
                    this.RaisePropertyChanged("KendiAnlikKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Airbag {
            get {
                return this.AirbagField;
            }
            set {
                if ((this.AirbagField.Equals(value) != true)) {
                    this.AirbagField = value;
                    this.RaisePropertyChanged("Airbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal GunlukKiralikFiyat {
            get {
                return this.GunlukKiralikFiyatField;
            }
            set {
                if ((this.GunlukKiralikFiyatField.Equals(value) != true)) {
                    this.GunlukKiralikFiyatField = value;
                    this.RaisePropertyChanged("GunlukKiralikFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string SirketAdi {
            get {
                return this.SirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdiField, value) != true)) {
                    this.SirketAdiField = value;
                    this.RaisePropertyChanged("SirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool RezerveDurumu {
            get {
                return this.RezerveDurumuField;
            }
            set {
                if ((this.RezerveDurumuField.Equals(value) != true)) {
                    this.RezerveDurumuField = value;
                    this.RaisePropertyChanged("RezerveDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Resim {
            get {
                return this.ResimField;
            }
            set {
                if ((object.ReferenceEquals(this.ResimField, value) != true)) {
                    this.ResimField = value;
                    this.RaisePropertyChanged("Resim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RezervasyonViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RezervasyonViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KiralikIdField;
        
        private int AracIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusteriAdSoyadField;
        
        private int EhliyetYasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        private System.DateTime Alis_TarihiField;
        
        private System.DateTime Veris_TarihiField;
        
        private int VerilisKmField;
        
        private decimal AlinanUcretField;
        
        private bool IadeField;
        
        private bool KabulDurumuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KiralikId {
            get {
                return this.KiralikIdField;
            }
            set {
                if ((this.KiralikIdField.Equals(value) != true)) {
                    this.KiralikIdField = value;
                    this.RaisePropertyChanged("KiralikId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AracId {
            get {
                return this.AracIdField;
            }
            set {
                if ((this.AracIdField.Equals(value) != true)) {
                    this.AracIdField = value;
                    this.RaisePropertyChanged("AracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MusteriAdSoyad {
            get {
                return this.MusteriAdSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriAdSoyadField, value) != true)) {
                    this.MusteriAdSoyadField = value;
                    this.RaisePropertyChanged("MusteriAdSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EhliyetYasi {
            get {
                return this.EhliyetYasiField;
            }
            set {
                if ((this.EhliyetYasiField.Equals(value) != true)) {
                    this.EhliyetYasiField = value;
                    this.RaisePropertyChanged("EhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime Alis_Tarihi {
            get {
                return this.Alis_TarihiField;
            }
            set {
                if ((this.Alis_TarihiField.Equals(value) != true)) {
                    this.Alis_TarihiField = value;
                    this.RaisePropertyChanged("Alis_Tarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime Veris_Tarihi {
            get {
                return this.Veris_TarihiField;
            }
            set {
                if ((this.Veris_TarihiField.Equals(value) != true)) {
                    this.Veris_TarihiField = value;
                    this.RaisePropertyChanged("Veris_Tarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int VerilisKm {
            get {
                return this.VerilisKmField;
            }
            set {
                if ((this.VerilisKmField.Equals(value) != true)) {
                    this.VerilisKmField = value;
                    this.RaisePropertyChanged("VerilisKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal AlinanUcret {
            get {
                return this.AlinanUcretField;
            }
            set {
                if ((this.AlinanUcretField.Equals(value) != true)) {
                    this.AlinanUcretField = value;
                    this.RaisePropertyChanged("AlinanUcret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Iade {
            get {
                return this.IadeField;
            }
            set {
                if ((this.IadeField.Equals(value) != true)) {
                    this.IadeField = value;
                    this.RaisePropertyChanged("Iade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool KabulDurumu {
            get {
                return this.KabulDurumuField;
            }
            set {
                if ((this.KabulDurumuField.Equals(value) != true)) {
                    this.KabulDurumuField = value;
                    this.RaisePropertyChanged("KabulDurumu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RezervWebService.AracWebServiceSoap")]
    public interface AracWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCar", ReplyAction="*")]
        AracKiralamaSOAP.RezervWebService.InsertCarResponse InsertCar(AracKiralamaSOAP.RezervWebService.InsertCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCar", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.InsertCarResponse> InsertCarAsync(AracKiralamaSOAP.RezervWebService.InsertCarRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCar", ReplyAction="*")]
        AracKiralamaSOAP.RezervWebService.UpdateCarResponse UpdateCar(AracKiralamaSOAP.RezervWebService.UpdateCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCar", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.UpdateCarResponse> UpdateCarAsync(AracKiralamaSOAP.RezervWebService.UpdateCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCar", ReplyAction="*")]
        bool DeleteCar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCarAsync(int id);
        
        // CODEGEN: Generating message contract since element name rezerv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RezervYap", ReplyAction="*")]
        AracKiralamaSOAP.RezervWebService.RezervYapResponse RezervYap(AracKiralamaSOAP.RezervWebService.RezervYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RezervYap", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.RezervYapResponse> RezervYapAsync(AracKiralamaSOAP.RezervWebService.RezervYapRequest request);
        
        // CODEGEN: Generating message contract since element name SelectAllCarsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCars", ReplyAction="*")]
        AracKiralamaSOAP.RezervWebService.SelectAllCarsResponse SelectAllCars(AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCars", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectAllCarsResponse> SelectAllCarsAsync(AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest request);
        
        // CODEGEN: Generating message contract since element name SelectAllRezervResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllRezerv", ReplyAction="*")]
        AracKiralamaSOAP.RezervWebService.SelectAllRezervResponse SelectAllRezerv(AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllRezerv", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectAllRezervResponse> SelectAllRezervAsync(AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest request);
        
        // CODEGEN: Generating message contract since element name SelectCarByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCarById", ReplyAction="*")]
        AracKiralamaSOAP.RezervWebService.SelectCarByIdResponse SelectCarById(AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCarById", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectCarByIdResponse> SelectCarByIdAsync(AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCar", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.InsertCarRequestBody Body;
        
        public InsertCarRequest() {
        }
        
        public InsertCarRequest(AracKiralamaSOAP.RezervWebService.InsertCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSOAP.RezervWebService.Arac entity;
        
        public InsertCarRequestBody() {
        }
        
        public InsertCarRequestBody(AracKiralamaSOAP.RezervWebService.Arac entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCarResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.InsertCarResponseBody Body;
        
        public InsertCarResponse() {
        }
        
        public InsertCarResponse(AracKiralamaSOAP.RezervWebService.InsertCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertCarResult;
        
        public InsertCarResponseBody() {
        }
        
        public InsertCarResponseBody(bool InsertCarResult) {
            this.InsertCarResult = InsertCarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCar", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.UpdateCarRequestBody Body;
        
        public UpdateCarRequest() {
        }
        
        public UpdateCarRequest(AracKiralamaSOAP.RezervWebService.UpdateCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSOAP.RezervWebService.Arac entity;
        
        public UpdateCarRequestBody() {
        }
        
        public UpdateCarRequestBody(AracKiralamaSOAP.RezervWebService.Arac entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCarResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.UpdateCarResponseBody Body;
        
        public UpdateCarResponse() {
        }
        
        public UpdateCarResponse(AracKiralamaSOAP.RezervWebService.UpdateCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCarResult;
        
        public UpdateCarResponseBody() {
        }
        
        public UpdateCarResponseBody(bool UpdateCarResult) {
            this.UpdateCarResult = UpdateCarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RezervYapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RezervYap", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.RezervYapRequestBody Body;
        
        public RezervYapRequest() {
        }
        
        public RezervYapRequest(AracKiralamaSOAP.RezervWebService.RezervYapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RezervYapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSOAP.RezervWebService.RezervasyonViewModel rezerv;
        
        public RezervYapRequestBody() {
        }
        
        public RezervYapRequestBody(AracKiralamaSOAP.RezervWebService.RezervasyonViewModel rezerv) {
            this.rezerv = rezerv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RezervYapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RezervYapResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.RezervYapResponseBody Body;
        
        public RezervYapResponse() {
        }
        
        public RezervYapResponse(AracKiralamaSOAP.RezervWebService.RezervYapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RezervYapResponseBody {
        
        public RezervYapResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCars", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.SelectAllCarsRequestBody Body;
        
        public SelectAllCarsRequest() {
        }
        
        public SelectAllCarsRequest(AracKiralamaSOAP.RezervWebService.SelectAllCarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllCarsRequestBody {
        
        public SelectAllCarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.SelectAllCarsResponseBody Body;
        
        public SelectAllCarsResponse() {
        }
        
        public SelectAllCarsResponse(AracKiralamaSOAP.RezervWebService.SelectAllCarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllCarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSOAP.RezervWebService.Arac[] SelectAllCarsResult;
        
        public SelectAllCarsResponseBody() {
        }
        
        public SelectAllCarsResponseBody(AracKiralamaSOAP.RezervWebService.Arac[] SelectAllCarsResult) {
            this.SelectAllCarsResult = SelectAllCarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRezervRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllRezerv", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.SelectAllRezervRequestBody Body;
        
        public SelectAllRezervRequest() {
        }
        
        public SelectAllRezervRequest(AracKiralamaSOAP.RezervWebService.SelectAllRezervRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllRezervRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sirketId;
        
        public SelectAllRezervRequestBody() {
        }
        
        public SelectAllRezervRequestBody(int sirketId) {
            this.sirketId = sirketId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRezervResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllRezervResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.SelectAllRezervResponseBody Body;
        
        public SelectAllRezervResponse() {
        }
        
        public SelectAllRezervResponse(AracKiralamaSOAP.RezervWebService.SelectAllRezervResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllRezervResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSOAP.RezervWebService.RezervasyonViewModel[] SelectAllRezervResult;
        
        public SelectAllRezervResponseBody() {
        }
        
        public SelectAllRezervResponseBody(AracKiralamaSOAP.RezervWebService.RezervasyonViewModel[] SelectAllRezervResult) {
            this.SelectAllRezervResult = SelectAllRezervResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCarByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCarById", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.SelectCarByIdRequestBody Body;
        
        public SelectCarByIdRequest() {
        }
        
        public SelectCarByIdRequest(AracKiralamaSOAP.RezervWebService.SelectCarByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCarByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SelectCarByIdRequestBody() {
        }
        
        public SelectCarByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCarByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCarByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSOAP.RezervWebService.SelectCarByIdResponseBody Body;
        
        public SelectCarByIdResponse() {
        }
        
        public SelectCarByIdResponse(AracKiralamaSOAP.RezervWebService.SelectCarByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCarByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSOAP.RezervWebService.Arac SelectCarByIdResult;
        
        public SelectCarByIdResponseBody() {
        }
        
        public SelectCarByIdResponseBody(AracKiralamaSOAP.RezervWebService.Arac SelectCarByIdResult) {
            this.SelectCarByIdResult = SelectCarByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracWebServiceSoapChannel : AracKiralamaSOAP.RezervWebService.AracWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracWebServiceSoapClient : System.ServiceModel.ClientBase<AracKiralamaSOAP.RezervWebService.AracWebServiceSoap>, AracKiralamaSOAP.RezervWebService.AracWebServiceSoap {
        
        public AracWebServiceSoapClient() {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSOAP.RezervWebService.InsertCarResponse AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.InsertCar(AracKiralamaSOAP.RezervWebService.InsertCarRequest request) {
            return base.Channel.InsertCar(request);
        }
        
        public bool InsertCar(AracKiralamaSOAP.RezervWebService.Arac entity) {
            AracKiralamaSOAP.RezervWebService.InsertCarRequest inValue = new AracKiralamaSOAP.RezervWebService.InsertCarRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.InsertCarRequestBody();
            inValue.Body.entity = entity;
            AracKiralamaSOAP.RezervWebService.InsertCarResponse retVal = ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).InsertCar(inValue);
            return retVal.Body.InsertCarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.InsertCarResponse> AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.InsertCarAsync(AracKiralamaSOAP.RezervWebService.InsertCarRequest request) {
            return base.Channel.InsertCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.InsertCarResponse> InsertCarAsync(AracKiralamaSOAP.RezervWebService.Arac entity) {
            AracKiralamaSOAP.RezervWebService.InsertCarRequest inValue = new AracKiralamaSOAP.RezervWebService.InsertCarRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.InsertCarRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).InsertCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSOAP.RezervWebService.UpdateCarResponse AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.UpdateCar(AracKiralamaSOAP.RezervWebService.UpdateCarRequest request) {
            return base.Channel.UpdateCar(request);
        }
        
        public bool UpdateCar(AracKiralamaSOAP.RezervWebService.Arac entity) {
            AracKiralamaSOAP.RezervWebService.UpdateCarRequest inValue = new AracKiralamaSOAP.RezervWebService.UpdateCarRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.UpdateCarRequestBody();
            inValue.Body.entity = entity;
            AracKiralamaSOAP.RezervWebService.UpdateCarResponse retVal = ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).UpdateCar(inValue);
            return retVal.Body.UpdateCarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.UpdateCarResponse> AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.UpdateCarAsync(AracKiralamaSOAP.RezervWebService.UpdateCarRequest request) {
            return base.Channel.UpdateCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.UpdateCarResponse> UpdateCarAsync(AracKiralamaSOAP.RezervWebService.Arac entity) {
            AracKiralamaSOAP.RezervWebService.UpdateCarRequest inValue = new AracKiralamaSOAP.RezervWebService.UpdateCarRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.UpdateCarRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).UpdateCarAsync(inValue);
        }
        
        public bool DeleteCar(int id) {
            return base.Channel.DeleteCar(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCarAsync(int id) {
            return base.Channel.DeleteCarAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSOAP.RezervWebService.RezervYapResponse AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.RezervYap(AracKiralamaSOAP.RezervWebService.RezervYapRequest request) {
            return base.Channel.RezervYap(request);
        }
        
        public void RezervYap(AracKiralamaSOAP.RezervWebService.RezervasyonViewModel rezerv) {
            AracKiralamaSOAP.RezervWebService.RezervYapRequest inValue = new AracKiralamaSOAP.RezervWebService.RezervYapRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.RezervYapRequestBody();
            inValue.Body.rezerv = rezerv;
            AracKiralamaSOAP.RezervWebService.RezervYapResponse retVal = ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).RezervYap(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.RezervYapResponse> AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.RezervYapAsync(AracKiralamaSOAP.RezervWebService.RezervYapRequest request) {
            return base.Channel.RezervYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.RezervYapResponse> RezervYapAsync(AracKiralamaSOAP.RezervWebService.RezervasyonViewModel rezerv) {
            AracKiralamaSOAP.RezervWebService.RezervYapRequest inValue = new AracKiralamaSOAP.RezervWebService.RezervYapRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.RezervYapRequestBody();
            inValue.Body.rezerv = rezerv;
            return ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).RezervYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSOAP.RezervWebService.SelectAllCarsResponse AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.SelectAllCars(AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest request) {
            return base.Channel.SelectAllCars(request);
        }
        
        public AracKiralamaSOAP.RezervWebService.Arac[] SelectAllCars() {
            AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest inValue = new AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.SelectAllCarsRequestBody();
            AracKiralamaSOAP.RezervWebService.SelectAllCarsResponse retVal = ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).SelectAllCars(inValue);
            return retVal.Body.SelectAllCarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectAllCarsResponse> AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.SelectAllCarsAsync(AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest request) {
            return base.Channel.SelectAllCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectAllCarsResponse> SelectAllCarsAsync() {
            AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest inValue = new AracKiralamaSOAP.RezervWebService.SelectAllCarsRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.SelectAllCarsRequestBody();
            return ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).SelectAllCarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSOAP.RezervWebService.SelectAllRezervResponse AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.SelectAllRezerv(AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest request) {
            return base.Channel.SelectAllRezerv(request);
        }
        
        public AracKiralamaSOAP.RezervWebService.RezervasyonViewModel[] SelectAllRezerv(int sirketId) {
            AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest inValue = new AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.SelectAllRezervRequestBody();
            inValue.Body.sirketId = sirketId;
            AracKiralamaSOAP.RezervWebService.SelectAllRezervResponse retVal = ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).SelectAllRezerv(inValue);
            return retVal.Body.SelectAllRezervResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectAllRezervResponse> AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.SelectAllRezervAsync(AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest request) {
            return base.Channel.SelectAllRezervAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectAllRezervResponse> SelectAllRezervAsync(int sirketId) {
            AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest inValue = new AracKiralamaSOAP.RezervWebService.SelectAllRezervRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.SelectAllRezervRequestBody();
            inValue.Body.sirketId = sirketId;
            return ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).SelectAllRezervAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSOAP.RezervWebService.SelectCarByIdResponse AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.SelectCarById(AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest request) {
            return base.Channel.SelectCarById(request);
        }
        
        public AracKiralamaSOAP.RezervWebService.Arac SelectCarById(int id) {
            AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest inValue = new AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.SelectCarByIdRequestBody();
            inValue.Body.id = id;
            AracKiralamaSOAP.RezervWebService.SelectCarByIdResponse retVal = ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).SelectCarById(inValue);
            return retVal.Body.SelectCarByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectCarByIdResponse> AracKiralamaSOAP.RezervWebService.AracWebServiceSoap.SelectCarByIdAsync(AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest request) {
            return base.Channel.SelectCarByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSOAP.RezervWebService.SelectCarByIdResponse> SelectCarByIdAsync(int id) {
            AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest inValue = new AracKiralamaSOAP.RezervWebService.SelectCarByIdRequest();
            inValue.Body = new AracKiralamaSOAP.RezervWebService.SelectCarByIdRequestBody();
            inValue.Body.id = id;
            return ((AracKiralamaSOAP.RezervWebService.AracWebServiceSoap)(this)).SelectCarByIdAsync(inValue);
        }
    }
}
